import express, { Request, Response } from 'express';
import cors from 'cors';
import path from 'path';
import { ENV } from './env';
import router from './routes'; 
import 'dotenv/config';

const app = express();

// 1. Middleware
app.use(cors());
app.use(express.json());

// 2. Boot Logging (Critical for debugging Azure Environment Variables)
console.log('[BOOT] Initializing Server...');
console.log('[BOOT] Environment Check:', {
  PORT: process.env.PORT || 8787,
  DATABRICKS_HOST: !!ENV.DATABRICKS_HOSTNAME,
  DATABRICKS_PATH: !!ENV.DATABRICKS_HTTP_PATH,
  DATABRICKS_TOKEN: !!ENV.DATABRICKS_TOKEN,
  NODE_ENV: process.env.NODE_ENV
});

// 3. API Routes
// All your databricks logic from routes.ts will be under /api
app.use('/api', router);

// 4. Enhanced Health Check
app.get('/api/health', (_req: Request, res: Response) => {
  const isConfigured = !!ENV.DATABRICKS_HOSTNAME && !!ENV.DATABRICKS_TOKEN;
  res.status(isConfigured ? 200 : 500).json({
    status: isConfigured ? 'healthy' : 'unhealthy',
    database: isConfigured ? 'configured' : 'missing_credentials',
    timestamp: new Date().toISOString(),
    uptime: process.uptime()
  });
});

// 5. Serve Static Files (The fix for the "Waiting for Content" screen)
// This points to the 'client/dist' folder generated by your Vite build
const clientDistPath = path.join(__dirname, '../../client/dist');
app.use(express.static(clientDistPath));

// Handle SPA routing (Send all non-API requests to index.html)
app.get('*', (req, res) => {
  if (!req.path.startsWith('/api')) {
    res.sendFile(path.join(clientDistPath, 'index.html'));
  }
});

// 6. Start Server
const PORT = Number(process.env.PORT || 8787);
const server = app.listen(PORT, '0.0.0.0', () => {
  console.log(`🚀 Server is flying at http://0.0.0.0:${PORT}`);
  console.log(`Serving static files from: ${clientDistPath}`);
});

// Global Error Handling
process.on('unhandledRejection', (reason) => {
  console.error('[FATAL] Unhandled Rejection:', reason);
});

server.on('error', (err) => {
  console.error('[SERVER ERROR]:', err);
});
